# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Human-X Interactions Laboratory
author: DLSU HXIL 
email: hxil AT dlsu.edu.ph
description: >- # this means to ignore newlines until "baseurl:"
  The Human-X Interactions Lab is an interdisciplinary research lab within the Advanced Research Institute for Informatics, Computing, and Networking at De La Salle University. We investigate how humans learn, integrate, and interact with emerging technologies beyond traditional digital devicesâ€”robots, drones, smart spaces, and AI, among others. 
tagline: Pioneering and leveraging computing research in Human-Computer Interaction to improve the way we move, work, create and participate in society.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dlsu-hxil.org" # changed from "http://comet.dlsu.edu.ph" # the base hostname & protocol for your site, e.g. http://example.com
permalink: pretty

# Social settings
social_sites:
  twitter: dlsu_comet
  github:  dlsucomet
  facebook: dlsuhxil

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
# Kramdown settings
kramdown:
  input: GFM

# Disqus
disqus:
  shortname: dlsu-hxil-org

# Google Analytics
google_analytics: UA-134064054-1

# Highlighter settings
highlighter: rouge

exclude: [vendor]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
